export interface P15MatrixRow {
  readonly id: string;
  readonly area: 'reasoning' | 'text' | 'stop' | 'context' | 'config' | 'session' | 'ux';
  readonly requirement: string;
  readonly contractEvidence: string;
  readonly runtimeEvidence: string;
}

export const P15_TEST_MATRIX: readonly P15MatrixRow[] = [
  {
    id: 'RSN-01',
    area: 'reasoning',
    requirement: 'reasoning strings are concatenated in arrival order without trim',
    contractEvidence: 'docs/plans/p1-5-reasoning-context.md',
    runtimeEvidence: 'tests/unit/provider/openai-compatible-provider.test.ts',
  },
  {
    id: 'RSN-02',
    area: 'reasoning',
    requirement: 'reasoning_content is aggregated and mapped back on the next request',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/provider/request-mapping.test.ts',
  },
  {
    id: 'RSN-03',
    area: 'reasoning',
    requirement:
      'equivalent plain reasoning.text details normalize to canonical reasoning; special or mismatched arrays preserve order and structure',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/provider/reasoning.test.ts',
  },
  {
    id: 'RSN-04',
    area: 'reasoning',
    requirement: 'one model response persists at most one model.reasoning event',
    contractEvidence: 'docs/decisions/0006-reasoning-session-events.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'RSN-05',
    area: 'reasoning',
    requirement: 'reasoning never enters model.text_delta or CLI output',
    contractEvidence: 'docs/cli-ux.md',
    runtimeEvidence: 'tests/unit/cli/event-renderer.test.ts',
  },
  {
    id: 'RSN-06',
    area: 'reasoning',
    requirement: 'reasoning is written to JSONL and restored into the next projection',
    contractEvidence: 'docs/architecture.md',
    runtimeEvidence: 'tests/unit/context/event-context-builder.test.ts',
  },
  {
    id: 'RSN-07',
    area: 'reasoning',
    requirement: 'reasoning, tool call, and tool result are replayed together on the next step',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'RSN-08',
    area: 'reasoning',
    requirement: 'already received reasoning is kept when the stream fails or is cancelled',
    contractEvidence: 'docs/plans/p1-5-reasoning-context.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'TXT-01',
    area: 'text',
    requirement: 'any number of text deltas persist at most one model.text per response',
    contractEvidence: 'docs/plans/p1-5-reasoning-context.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'TXT-02',
    area: 'text',
    requirement: 'the version-3 writer never persists model.text_delta',
    contractEvidence: 'docs/decisions/0006-reasoning-session-events.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'TXT-03',
    area: 'text',
    requirement: 'stream failure or cancellation persists one partial:true aggregated body',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'TXT-04',
    area: 'text',
    requirement: 'v1/v2 and pre-revision v3 model.text_delta logs remain recoverable',
    contractEvidence: 'docs/decisions/0006-reasoning-session-events.md',
    runtimeEvidence: 'tests/unit/session/jsonl-session-repository.test.ts',
  },
  {
    id: 'TXT-05',
    area: 'text',
    requirement: 'mixing aggregated text and text deltas in one step is rejected as corrupt',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/session/session-query.test.ts',
  },
  {
    id: 'TXT-06',
    area: 'text',
    requirement: 'CLI display of aggregated text matches the previous stdout/stderr contract',
    contractEvidence: 'docs/cli-ux.md',
    runtimeEvidence: 'tests/unit/cli/event-renderer.test.ts',
  },
  {
    id: 'STOP-01',
    area: 'stop',
    requirement: 'reasoning-only length finishes as a provider failure, not completed',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'STOP-02',
    area: 'stop',
    requirement: 'visible content plus length returns limited with the partial body',
    contractEvidence: 'docs/cli-ux.md',
    runtimeEvidence: 'tests/integration/cli-run.test.ts',
  },
  {
    id: 'STOP-03',
    area: 'stop',
    requirement: 'tool call plus length does not execute the tool',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'STOP-04',
    area: 'stop',
    requirement: 'stop plus empty content returns PROVIDER_EMPTY_RESPONSE',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'STOP-05',
    area: 'stop',
    requirement: 'content_filter returns a provider failure',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/agent/agent-loop.test.ts',
  },
  {
    id: 'CTX-01',
    area: 'context',
    requirement: 'empty or failed turns still project their user goal into the next turn',
    contractEvidence: 'docs/architecture.md',
    runtimeEvidence: 'tests/unit/context/event-context-builder.test.ts',
  },
  {
    id: 'CTX-02',
    area: 'context',
    requirement: 'reasoning fields are included in approximateTokens',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/context/event-context-builder.test.ts',
  },
  {
    id: 'CTX-03',
    area: 'context',
    requirement: 'reasoning, tool calls, and results are never projected as isolated messages',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/context/event-context-builder.test.ts',
  },
  {
    id: 'CFG-01',
    area: 'config',
    requirement: 'built-in defaults are 256K / 16K / 40K approximate budgets',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/config/load-config.test.ts',
  },
  {
    id: 'CFG-02',
    area: 'config',
    requirement: 'explicit older positive integers continue to override defaults',
    contractEvidence: 'docs/contracts.md',
    runtimeEvidence: 'tests/unit/config/load-config.test.ts',
  },
  {
    id: 'SES-01',
    area: 'session',
    requirement: 'version 3 sessions round-trip model.reasoning',
    contractEvidence: 'docs/decisions/0006-reasoning-session-events.md',
    runtimeEvidence: 'tests/unit/session/jsonl-session-repository.test.ts',
  },
  {
    id: 'SES-02',
    area: 'session',
    requirement: 'version 2 sessions remain readable and resumable without invented reasoning',
    contractEvidence: 'docs/decisions/0006-reasoning-session-events.md',
    runtimeEvidence: 'tests/unit/session/jsonl-session-repository.test.ts',
  },
  {
    id: 'UX-01',
    area: 'ux',
    requirement: 'Chat no longer renders a blank ECHO for empty completed turns',
    contractEvidence: 'docs/cli-ux.md',
    runtimeEvidence: 'tests/integration/cli-chat.test.ts',
  },
  {
    id: 'UX-02',
    area: 'ux',
    requirement: '/status shows only ~used / limit for context',
    contractEvidence: 'docs/cli-ux.md',
    runtimeEvidence: 'tests/unit/cli/chat-view.test.ts',
  },
];
